# Generated by Django 3.0.3 on 2020-03-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.TextField(default='https://cdn.pixabay.com/photo/2017/01/11/12/05/emoji-1971624_960_720.png')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(default=None, max_length=255)),
                ('title', models.TextField()),
                ('date', models.CharField(max_length=255)),
                ('location', models.CharField(default=None, max_length=255)),
                ('address', models.CharField(default=None, max_length=255)),
                ('more_info', models.TextField(default='more info')),
                ('picture', models.TextField(default='some picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='eventune_app.User')),
            ],
        ),
    ]
