# Generated by Django 3.0.3 on 2020-02-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventune_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='more_info',
            field=models.TextField(default='more info'),
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.TextField(default='some picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(default='some profile pic'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(),
        ),
    ]
