# Generated by Django 3.0.3 on 2020-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventune_app', '0002_auto_20200225_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='api_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
