# Generated by Django 3.0.3 on 2020-02-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventune_app', '0003_event_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2017/01/11/12/05/emoji-1971624_960_720.png'),
        ),
    ]
