# Generated by Django 3.0.3 on 2020-02-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventune_app', '0004_auto_20200227_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
